### ISSUE TITLE
Strange lutaml-model behavior with child integer values not filled

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/reqif#2]
Notice this:

```ruby
xml = <<~XML
      <DATATYPE-DEFINITION-STRING IDENTIFIER="dt1" LAST-CHANGE="2023-10-26T12:00:00Z" LONG-NAME="String Type">
          <MAX-LENGTH>255</MAX-LENGTH>
        </DATATYPE-DEFINITION-STRING>
    XML

> Reqif::DatatypeDefinitionString.from_xml(xml)
# =>
#<Reqif::DatatypeDefinitionString:0x0000000124033520
 @alternative_id=nil,
 @desc=nil,
 @element_order=["text", "MAX-LENGTH", "text"],
 @identifier="dt1",
 @last_change=#<DateTime: 2023-10-26T12:00:00+00:00 ((2460244j,43200s,0n),+0s,2299161j)>,
 @long_name="String Type",
 @max_length=255,
 @mixed=nil,
 @ordered=nil,
 @using_default={:desc=>true, :identifier=>false, :last_change=>false, :long_name=>false, :max_length=>false, :alternative_id=>true}>
```

Notice that `max_length` is 255.

However, when this is embedded in a parent element:

```ruby
xml =     <<~XML
      <DATATYPES xmlns="http://www.omg.org/spec/ReqIF/20110401/reqif.xsd">
        <DATATYPE-DEFINITION-STRING IDENTIFIER="dt1" LAST-CHANGE="2023-10-26T12:00:00Z" LONG-NAME="String Type">
          <MAX-LENGTH>255</MAX-LENGTH>
        </DATATYPE-DEFINITION-STRING>
        <DATATYPE-DEFINITION-INTEGER IDENTIFIER="dt2" LAST-CHANGE="2023-10-26T12:00:00Z" LONG-NAME="Integer Type">
          <MAX>100</MAX>
          <MIN>0</MIN>
        </DATATYPE-DEFINITION-INTEGER>
      </DATATYPES>
    XML

> Reqif::Datatypes.from_xml(xml)

# =>
 [#<Reqif::DatatypeDefinitionString:0x00000001236ba3e0
    @alternative_id=nil,
    @desc=nil,
    @element_order=["text", "MAX-LENGTH", "text"],
    @identifier="dt1",
    @last_change=#<DateTime: 2023-10-26T12:00:00+00:00 ((2460244j,43200s,0n),+0s,2299161j)>,
    @long_name="String Type",
    @max_length=nil,
    @mixed=nil,
    @ordered=nil,
    @using_default={:desc=>true, :identifier=>false, :last_change=>false, :long_name=>false, :max_length=>true, :alternative_id=>true}>],
```

The `DatatypeDefinitionString` element has `max_length` of `nil. The other attributes are identical to the element when it is stand alone.

I'm using the latest lutaml-model version 0.3.28.

**Comment by HassanAkbar** [comment]
@ronaldtse Can I get the Model classes (`Reqif::DatatypeDefinitionString` and `Reqif::Datatypes`) or link to them for testing this? Thanks

**Comment by HassanAkbar** [comment]
@ronaldtse By looking at the code I think the issue is that the `MAX-LENGTH` is being  mapped as attribute here -> [datatype_definition_string.rb#L20](https://github.com/lutaml/reqif/blob/main/lib/reqif/datatype_definition_string.rb#L20), As attributes need explicit `namespace` so it is not being mapped when added to a parent element with a namespace. We need to change it to `map_element` and It will start working.

**Comment by ronaldtse** [comment]
Thank you! Didn’t realize it is that kind of problem. Will check.

**Comment by ronaldtse** [comment]
However, why would it work when it is not a nested class? We seem to be doing something different whether it is nested or not.

**Comment by HassanAkbar** [comment]
@ronaldtse From `lutaml-model` documentation 

> The map_attribute method does not inherit the root element’s namespace. To specify a namespace for an attribute, please explicitly declare the namespace and prefix in the map_attribute method.

Our internal representation is a hash and we do not differentiate between the attributes and elements they are just key-value pairs. So when we try to parse it directly without the nested class it does not have a namespace present and gets parsed correctly.

**Comment by ronaldtse** [comment]
@HassanAkbar but the non-differentiation is still very strange because it causes inconsistent expectation: `map_attribute` is not meant to support `map_element`. This will be a problem if an object will both have an attribute and an element of the same name. We should add a test to test that.

**Comment by HassanAkbar** [comment]
@ronaldtse I agree. While working on the `map_all_attributes` functionality, I faced the same issue, so I separated the `elements` and `attributes` in that branch. 
I'll add a test case for this in that PR.

**Comment by ronaldtse** [comment]
Actually the ReqIF format is strange here:

<img width="388" alt="Screenshot 2024-11-28 at 4 16 52 PM" src="https://github.com/user-attachments/assets/dd8a74b5-9d36-4936-9de9-0d775becccec">

Notice that the tests from EA exports and the StrictDocs project use the attribute `MAX-LENGTH`, but the IBM Doors export and Eclipse RMF use the element `<MAX-LENGTH>`.

From the ReqIF XSD, `MAX-LENGTH` is an attribute:
* https://www.omg.org/spec/ReqIF/20110401/reqif.xsd

<img width="616" alt="Screenshot 2024-11-28 at 4 20 20 PM" src="https://github.com/user-attachments/assets/2519f5c8-4399-48e8-8ac7-8f1c8237199c">

Similarly in the PDF:
* https://www.omg.org/spec/ReqIF/1.2/PDF

<img width="889" alt="Screenshot 2024-11-28 at 4 20 52 PM" src="https://github.com/user-attachments/assets/4ac04708-cb5e-456e-a93d-be01cb24facd">

I'm going to delete those test files that are incompatible with the spec.
